version: '3'

services:
  oc-agent:
    image: ocagent:latest
    entrypoint: "/ocagent"
    command: ["--config=/conf/oc-agent-config.yaml"]
    ports:
      - 55678:55678
      - 55679:55679
    volumes:
      - ./config/oc-agent-config.yaml:/conf/oc-agent-config.yaml
    depends_on:
      - oc-collector
  oc-collector:
    image: omnition/opencensus-collector
    command: ["--debug-processor", "--config=/conf/oc-collector-config.yaml"]
    volumes:
      - ./config/oc-collector-config.yaml:/conf/oc-collector-config.yaml
    depends_on:
      - jaeger
  jaeger:
    image: jaegertracing/all-in-one:1.8
    ports:
      - 16686:16686
